### ISSUE TITLE
docker-compose upしたら大容量のtmpフォルダがローカル環境下に構築されてしまう

### ISSUE THREAD

**Issue by Tamatebako0205** [maho-na510/rubyPractice#1]
# 概要
現在、docker-compose upコマンドを使ったら大容量のtmpフォルダがローカル環境下に構築されてしまう

原因は下記docker-compose.ymlのコードのvolumes部分にある

```
version: "3.9"
services:
  db:
    container_name: rubyPractice_db
    image: postgres:12.4-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
```

# 改善策

以下のような名前付きボリュームに変更する

```
version: "3.9"
services:
  db:
    container_name: rubyPractice_db
    image: postgres:12.4-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass


volumes:
  db-data:
    driver: local
```

# 参考リンク

https://note.com/npaka/n/nbbdbeefde883
