### ISSUE TITLE
Rails newが実行されていないのでRailsアプリケーションがローカル環境下で構築できていない

### ISSUE THREAD

**Issue by Tamatebako0205** [maho-na510/rubyPractice#3]
# 背景
docker-compose upしてもrailsアプリケーションがローカルにマウントされていない

# 改善

## tty: trueモードに設定する

一度、docker-compose.ymlを以下の設定に変更する

```
version: "3.9"
services:
  db:
    container_name: rubyPractice_db
    image: postgres:12.4-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
      
  web:
    container_name: rubyPractice_web
    build: .
    tty: true 
    volumes:
      - .:/rubyPractice
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
    driver: local
```

commnads部分を削除しtty: trueモードで起動させrailsを上げなくてもコンテナが上がるよう対応する

## コンテナの中に入る
docker-compose upしてrailsコンテナの中に入る

```
docker-compose up
docker exec -ti rubyPractice_web /bin/bash
```

## rails new

rails newコマンドを実行し新規のrailsアプリケーションを作成する

```
rails new [アプリにつけたい名前]
```

## フォルダ構成の修正とdocker-compose.ymlの修正

作成したrailsアプリケーション
変更した
```
version: "3.9"
services:
  db:
    container_name: rubyPractice_db
    image: postgres:12.4-alpine
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pass
      
  web:
    container_name: rubyPractice_web
    build: app
    command: bash -c "cd  [アプリにつけたい名前]; rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/rubyPractice
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  db-data:
    driver: local
```

## GemfileとGemfile.lockを移動
GemfileとGemfile.lockを[アプリにつけたい名前]フォルダに移動
再度、docker-compose build

=> 上がらなかったので、以下のissuesに続きます
https://github.com/maho-na510/rubyPractice/issues/4
